[tasks.debug_build]
command = "cargo"
args = ["build", "--target", "wasm32-unknown-unknown"]

[tasks.debug_wasm]
command = "wasm-bindgen"
args = ["--target", "web", "--out-dir", "./examples", "target/wasm32-unknown-unknown/debug/bevy-timing-game.wasm"]

[tasks.debug]
dependencies = [
	"debug_build",
	"debug_wasm",
]

[tasks.release_build]
command = "cargo"
args = ["build", "--release", "--target", "wasm32-unknown-unknown"]

[tasks.release_wasm]
command = "wasm-bindgen"
args = ["--target", "web", "--out-dir", "./examples", "target/wasm32-unknown-unknown/release/bevy-timing-game.wasm"]

[tasks.release]
dependencies = [
	"release_build",
	"release_wasm",
]
